name: Comprehensive Version Calculation Tests

on: [push]

jobs:
  test-semver:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch_name: 'feature'
            jira_card: ''
            test_version: 'v0.1.0'
            expected_pattern: '0\.1\.1-feature-[a-fA-F0-9]{7,}.*'
          - branch_name: 'feature'
            jira_card: 'JIRA123'
            test_version: 'v0.1.0'
            expected_pattern: '0\.1\.1-featureJIRA123-[a-fA-F0-9]{7,}.*'
          - branch_name: 'feature'
            jira_card: 'JIRA-123'
            test_version: 'v0.1.0'
            expected_pattern: '0\.1\.1-featureJIRA123-[a-fA-F0-9]{7,}.*'
          - branch_name: 'develop'
            jira_card: ''
            test_version: 'v1.2.3'
            expected_pattern: '1\.2\.4-develop-[a-fA-F0-9]{7,}.*'
          - branch_name: 'release'
            jira_card: ''
            test_version: 'v2.0.0'
            expected_pattern: '2\.0\.1-release-[a-fA-F0-9]{7,}.*'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Version Calculation
        id: compute_version
        uses: ./
        with:
          test_branch_name: ${{ matrix.test_branch_name }}
          test_version_tag: ${{ matrix.test_version }}

      - name: Output Computed Version
        run: echo "Computed version for ${{ matrix.test_branch_name }} with latest release version ${{ matrix.test_version }} is '${{ steps.compute_version.outputs.version }}'"
      - name: Assert Computed Version
        run: |
          COMPUTED_VERSION="${{ steps.compute_version.outputs.version }}"
          EXPECTED_PATTERN="${{ matrix.expected_pattern }}"
          echo "Computed version: $COMPUTED_VERSION"
          echo "Expected pattern: $EXPECTED_PATTERN"
      
          if [[ "$COMPUTED_VERSION" =~ ^$EXPECTED_PATTERN$ ]]; then
            echo "✅ Computed version matches the expected pattern."
          else
            echo "❌ Computed version does not match the expected pattern."
            exit 1
          fi