name: Test Compute Version Action

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version_tag: ['1.2.3', '1.2.3-alpha.1', '1.2.3+20210101', '1.2.3-alpha.1+20210101']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Compute Version Action with Test Version Tag
      uses: ./.github/actions/compute-version@feature/aci-1-initial-compute-semver
      with:
        test_version_tag: ${{ matrix.version_tag }}
